// 非浏览器交互测试：轻量DOM适配器验证事件、状态及恢复。不能代替真实排版验证。
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('outputs/西马45天整合学习网页.html','utf8');
const decode=s=>s.replace(/&(?:amp|lt|gt|quot|#39);/g,x=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#39;':"'"}[x]));
const voids=new Set(['input','img','meta','link','br','hr']);
class E {
 constructor(tag='div',attrs={}){this.tag=tag;this.attrs=attrs;this.children=[];this.parent=null;this._value=null;this.checked='checked'in attrs;this.handlers={};}
 get id(){return this.attrs.id} get dataset(){let d={};for(let[k,v]of Object.entries(this.attrs))if(k.startsWith('data-'))d[k.slice(5).replace(/-([a-z])/g,(_,s)=>s.toUpperCase())]=v;return d;}
 get classList(){let e=this;return {add(c){e.attrs.class=[...new Set(((e.attrs.class||'')+' '+c).trim().split(/\s+/))].join(' ')},remove(c){e.attrs.class=(e.attrs.class||'').split(/\s+/).filter(x=>x!==c).join(' ')},contains(c){return (e.attrs.class||'').split(/\s+/).includes(c)},toggle(c,on){if(on)this.add(c);else this.remove(c)}};}
 set innerHTML(s){this.children=parse(s,this).children;}get innerHTML(){return this.children.map(serialize).join('');}
 get textContent(){return this.children.map(x=>typeof x==='string'?decode(x):x.textContent).join('');}set textContent(s){this.children=[String(s)];}
 get value(){if(this._value!==null)return this._value;if(this.tag==='textarea')return this.textContent;if(this.tag==='select'){let opts=this.querySelectorAll('option');let o=opts.find(o=>'selected'in o.attrs)||opts[0];return o?.attrs.value??o?.textContent??'';}return this.attrs.value||'';}set value(v){this._value=String(v)}
 querySelectorAll(sel){let parts=sel.split(/\s+/),last=parts.pop();return walk(this).filter(e=>matches(e,last)&&(!parts.length||ancestorMatches(e.parent,parts[parts.length-1])))}querySelector(s){return this.querySelectorAll(s)[0]||null}
 setAttribute(k,v){this.attrs[k]=String(v)}getAttribute(k){return this.attrs[k]}
 addEventListener(k,f){(this.handlers[k]??=[]).push(f)}focus(){}scrollIntoView(){}setSelectionRange(){}
 click(){if('disabled'in this.attrs)return;if(this.onclick)this.onclick({target:this});for(let f of this.handlers.click||[])f({target:this});}
 closest(s){let n=this;while(n){if(s.split(',').some(x=>matches(n,x)))return n;n=n.parent;}return null}
 insertAdjacentHTML(where,s){let nodes=parse(s).children;if(where==='afterbegin'){this.children.unshift(...nodes);nodes.forEach(n=>{if(typeof n!=='string')n.parent=this})}else if(where==='beforeend'){this.children.push(...nodes);nodes.forEach(n=>{if(typeof n!=='string')n.parent=this})}else{let p=this.parent;if(!p)return;let idx=p.children.indexOf(this)+(where==='afterend'?1:0);p.children.splice(idx,0,...nodes);nodes.forEach(n=>{if(typeof n!=='string')n.parent=p})}}
}
function walk(e){let r=[];for(let n of e.children)if(n instanceof E){r.push(n,...walk(n))}return r;}
function ancestorMatches(e,s){while(e){if(matches(e,s))return true;e=e.parent}return false}
function matches(e,s){if(!s||!e)return false;if(s.endsWith(':checked')){if(!e.checked)return false;s=s.slice(0,-8)}let at=[...s.matchAll(/\[([^=\]]+)(?:="([^"]*)")?\]/g)];for(let a of at)if(!(a[1]in e.attrs)||(a[2]!==undefined&&e.attrs[a[1]]!==a[2]))return false;s=s.replace(/\[[^\]]+\]/g,'');if(s.startsWith('#'))return e.id===s.slice(1);let a=s.split('.'),tag=a.shift();if(tag&&e.tag!==tag)return false;return a.every(c=>e.classList.contains(c));}
function parse(s,root=new E('root')){root.children=[];let stack=[root];for(let tok of String(s).match(/<[^>]*>|[^<]+/g)||[]){if(tok.startsWith('</')){if(stack.length>1)stack.pop();continue}if(tok.startsWith('<!'))continue;if(tok.startsWith('<')){let m=tok.match(/^<([a-zA-Z0-9-]+)/);if(!m)continue;let attrs={};for(let a of tok.slice(m[0].length,-1).matchAll(/([^\s=/>]+)(?:="([^"]*)"|='([^']*)'|=([^\s>]+))?/g))attrs[a[1]]=decode(a[2]??a[3]??a[4]??'');let n=new E(m[1],attrs),p=stack.at(-1);n.parent=p;p.children.push(n);if(!voids.has(n.tag)&&!tok.endsWith('/>'))stack.push(n)}else stack.at(-1).children.push(tok)}return root;}
function serialize(n){if(typeof n==='string')return n;let a=Object.entries(n.attrs).map(([k,v])=>` ${k}="${v}"`).join('');return `<${n.tag}${a}>${n.children.map(serialize).join('')}${voids.has(n.tag)?'':`</${n.tag}>`}`}
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
const doc=parse(html.replace(/<script>[\s\S]*?<\/script>/g,''));doc.getElementById=id=>walk(doc).find(x=>x.id===id)||null;doc.documentElement=doc.querySelector('html');doc.documentElement.style={setProperty(){}};doc.body=doc.querySelector('body');doc.body.style={};doc.createElement=tag=>new E(tag);
const alerts=[],storage=new Map();let ctx={document:doc,window:{scrollTo(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},alert:s=>alerts.push(s),setTimeout:f=>f(),console,Blob:class{},URL:{createObjectURL:()=>'',revokeObjectURL(){}},Map,Set,Date};vm.createContext(ctx);vm.runInContext(scripts.join('\n'),ctx);const run=s=>vm.runInContext(s,ctx);
assert(doc.getElementById('main').textContent.includes('第 1 天'));
run("setNav('questions')");assert(doc.getElementById('main').textContent.includes('372 道选择题'));assert.equal(doc.querySelectorAll('[data-openq]').length,20);
run("state.bank.filters.chapter='habermas';state.bank.filters.kind='选择题';state.bank.queue=[];renderQuestions()");assert.equal(run('filteredBank().length'),40);
run("startBank(['X-B02-1'])");doc.querySelector('[data-mark]').click();assert(run('state.bank.marks["X-B02-1"]'));for(let fn of doc.handlers.click||[])fn({target:doc.querySelector('[data-unit]')});assert(doc.getElementById('modalBody').textContent.includes('有效性'));doc.getElementById('closeSource').click();let q=run("qObject('X-B02-1')");doc.querySelector('[data-confidence]').value='很有把握';doc.querySelector('[data-confidence]').onchange();run(`selectQ('X-B02-1',${(q.a+1)%4})`);assert.equal(run('state.bank.history.length'),1);assert.equal(run('state.bank.review.B02.due'),2);assert(doc.getElementById('main').textContent.includes('逐项解析'));
let note=doc.getElementById('note-X-B02-1');note.value='我把真诚误作真理；下次先看证据';note.oninput();run("unitModal('B02')");assert(doc.getElementById('modalBody').textContent.includes('有效性'));doc.getElementById('closeSource').click();run('renderQuestions()');assert.equal(doc.getElementById('note-X-B02-1').value,'我把真诚误作真理；下次先看证据');
run("openRange('P0777-P0792')");assert(doc.getElementById('modalBody').textContent.includes('P0777'));doc.getElementById('closeSource').click();
run("state.day=2;state.bank.session++;selectQ('X-B02-1',qObject('X-B02-1').a)"); // 信心须主动填写，未填写不会新增记录
assert.equal(run('state.bank.history.length'),1);
run("state.bank.confidence[bankKey('X-B02-1')]='有些把握';selectQ('X-B02-1',qObject('X-B02-1').a)");assert.equal(run('state.bank.review.B02.due'),5);
run("state.bank.session++;state.bank.confidence[bankKey('X-B02-1')]='有些把握';selectQ('X-B02-1',qObject('X-B02-1').a)");assert.equal(run('state.bank.review.B02.due'),5);
for(let d of [5,12])run(`state.day=${d};state.bank.session++;state.bank.confidence[bankKey('X-B02-1')]='有些把握';selectQ('X-B02-1',qObject('X-B02-1').a)`);assert.equal(run('state.bank.review.B02'),undefined);assert(!run('weakUnits().some(x=>x.u.id==="B02")'));
run("state.day=15;startBank(['W-hork-E'])");doc.querySelector('[data-confidence]').value='有些把握';doc.querySelector('[data-confidence]').onchange();let draft=doc.querySelector('[data-draft]');draft.value='启蒙从解除恐惧出发，但手段计算可能变成唯一目的，文化工业通过标准化影响主体。';draft.oninput();doc.querySelector('[data-reveal]').click();assert(doc.getElementById('main').textContent.includes('考场参考答案'));let checks=doc.querySelectorAll('[data-rubric]');checks[0].checked=true;checks[1].checked=true;doc.querySelector('[data-self]').click();assert.equal(run("state.bank.self['W-hork-E'].score"),9);assert.equal(run("state.bank.essayReview['W-hork-E'].due"),16);
run("setNav('progress')");let backup=doc.getElementById('backupText').value;let parsed=JSON.parse(backup);assert.equal(parsed.bank.history.length,5);run('state.bank.notes={};');doc.getElementById('restoreText').value=backup;doc.getElementById('restorePasted').click();assert(doc.getElementById('restoreConfirm').textContent.includes('校验通过'));doc.getElementById('confirmRestore').click();assert.equal(run("state.bank.notes['X-B02-1']"),'我把真诚误作真理；下次先看证据');
assert(run('validateBackup({version:1,day:1,completed:[],stepDone:{}})'));assert.throws(()=>run('validateBackup({version:2,day:1,completed:[],stepDone:{},bank:{history:[{id:"X-B02-1",choice:9,day:1,correct:true,confidence:"很有把握"}]}})'));assert.throws(()=>run('validateBackup({version:2,day:1,completed:[],stepDone:{},bank:{review:{B02:{due:2,stage:10}}}})'));assert.throws(()=>run('validateBackup({version:2,day:999,completed:[],stepDone:{}})'));
for(let d=1;d<=45;d++){run(`state.day=${d};nav='today';state.activeStep=3;render()`);let ids=run(`dailyQuiz(DATA.days[${d-1}])`);assert(ids.length>=2&&ids.length<=3,`第${d}日题数`);assert.equal(run(`stepTime(DATA.days[${d-1}]).reduce((a,b)=>a+b,0)`),60);run('state.activeStep=4;render()');assert(doc.querySelector('[data-draft]'),`第${d}日大题`);}
run("nav='questions';state.bank.mode='覆盖表';state.bank.filters.chapter='all';renderQuestions()");assert(doc.getElementById('main').textContent.includes('G18'));assert(doc.getElementById('main').textContent.includes('U08'));
run("state.bank.mode='专题';state.bank.filters=bankFresh().filters;state.bank.filters.chapter='base';state.bank.filters.topic='G01';state.bank.filters.kind='选择题';state.bank.queue=[];renderQuestions()");doc.getElementById('start-bank').click();assert.equal(run('state.bank.queue.length'),4);assert(run('state.bank.queue.every(id=>QUESTIONS.get(id).kp.includes("G01"))'));
run("state.bank.mode='专题';state.bank.filters=bankFresh().filters;state.bank.filters.topic='跨理论比较';renderQuestions()");assert(run('filteredBank().some(q=>q.id==="X-luk-D4")'));run("state.bank.filters=bankFresh().filters;state.bank.filters.kind='选择题';state.bank.mode='混合';state.bank.queue=[];renderQuestions()");doc.getElementById('start-bank').click();assert(run('new Set(state.bank.queue.map(id=>QUESTIONS.get(id).chapter)).size')>=6);run("startBank(['W-hork-E'])");assert.equal(doc.querySelectorAll('[data-rubric]').length,0);assert.equal(run('state.bank.selfAttempts[bankKey("W-hork-E")]'),undefined);
run("nav='today';state.day=1;state.activeStep=6;[0,1,2,3,4,5].forEach(i=>state.stepDone[doneKey(1,i)]=true);render()");doc.getElementById('finishDay').click();assert.equal(run('state.day'),2);assert(run('state.completed.includes(1)'));
// 验证存储适配器保存的记录；不是实际浏览器 localStorage 测试。
assert(storage.get('ximarx-45-integrated-v1').includes('我把真诚'));
console.log('PASS：专题筛选、选择题反馈、微课/原文返回保留、草稿、逐点自评、复习1/3/7规则、同日不晋级、备份恢复、旧版本校验、45日60分钟与题目链接');
console.log('限制：这是轻量DOM适配器的逻辑验证，不验证浏览器存储策略、实际排版或手机触摸。');
