// 题库升级：复用原文、讲义与45日入口，学习记录与旧字段兼容。
const UNITS = new Map(DATA.knowledge.map(u=>[u.id,u]));
const QUESTIONS = new Map([...DATA.quiz,...DATA.essays,...DATA.legacyQuiz].map(q=>[q.id,q]));
function bankFresh(){return {attempts:{},drafts:{},revealed:{},marks:{},notes:{},confidence:{},self:{},selfAttempts:{},review:{},essayReview:{},history:[],dayVersions:{},filters:{chapter:'all',topic:'all',kind:'all',priority:'all',difficulty:'all',search:''},mode:'专题',queue:[],cursor:0,session:1,page:0}}
function normalizeBank(){state.version=2;state.bank=Object.assign(bankFresh(),state.bank||{});for(const k of ['attempts','drafts','revealed','marks','notes','confidence','self','selfAttempts','review','essayReview','dayVersions','filters'])state.bank[k]=Object.assign(bankFresh()[k],state.bank[k]||{});if(!Array.isArray(state.bank.history))state.bank.history=[];if(!Array.isArray(state.bank.queue))state.bank.queue=[];state.bank.queue=state.bank.queue.filter(id=>QUESTIONS.has(id));}
normalizeBank();
function bankKey(id){return (nav==='today'?'D'+state.day:'P'+state.bank.session)+'|'+id}
function priorityTag(p){return `<span class="tag priority-${p==='核心必会'?'core':p==='重点掌握'?'focus':'extra'}">【${esc(p)}】</span>`}
function questionMeta(q){return `<div class="row">${priorityTag(q.priority)}<span class="pill">${esc(q.difficulty)} · ${esc(q.kind)}</span><span class="tag tag-note">模拟题</span><span class="small muted">${esc(q.id)} · ${esc(q.topic)}</span><button class="btn secondary small" data-mark="${q.id}" type="button">${state.bank.marks[q.id]?'★ 已收藏':'☆ 收藏'}</button></div><p class="small muted">题干若含现实情境，均为教学假设；不据此证明理论成立。</p>`}
function qLinks(q){return `<div class="row small">${(q.kp||[]).map(k=>`<button class="source-link" data-unit="${esc(k)}" type="button">微课：${esc(UNITS.get(k).term)}</button><button class="source-link" data-lecture="${esc(k)}" type="button">展开相关讲义</button>`).join('')}<button class="source-link" data-range="${esc(q.ref)}" type="button">读原笔记 ${esc(q.ref)}</button></div>`}
function questionTools(q){return `<div class="row"><button class="btn secondary" data-repeat="${q.id}" type="button">独立再答一次</button></div><label for="note-${q.id}">我的解释、困惑与错因（自动保存）</label><textarea id="note-${q.id}" data-qnote="${q.id}" placeholder="写出你依赖哪条条件判断，或下一次如何辨别。">${esc(state.bank.notes[q.id]||'')}</textarea>`}
qObject=id=>QUESTIONS.get(id);
function firstStats(list=DATA.quiz){const valid=new Set(list.map(q=>q.id));const h=state.bank.history.filter(a=>valid.has(a.id));const first=new Map();h.forEach(a=>{if(!first.has(a.id))first.set(a.id,a)});const values=[...first.values()];return {done:values.length,correct:values.filter(a=>a.correct).length,rate:values.length?Math.round(values.filter(a=>a.correct).length/values.length*100):null}}
function weakUnits(){return DATA.knowledge.map(u=>{const ids=new Set(u.quizIds),latest=new Map();state.bank.history.filter(a=>ids.has(a.id)).forEach(a=>latest.set(a.id,a));const a=[...latest.values()],done=a.length,rate=done?Math.round(a.filter(x=>x.correct).length/done*100):null;return {done,rate,u}}).filter(x=>x.done&&x.rate<75).sort((a,b)=>a.rate-b.rate||b.done-a.done)}
function scheduleReview(q,correct){let b=state.bank;for(const k of q.kp||[]){let r=b.review[k];if(!correct){b.review[k]={due:state.day+1,stage:0,lastDay:state.day,failed:q.id};continue}if(r&&r.due<=state.day&&r.lastDay!==state.day){let stage=r.stage+1;if(stage>=3)delete b.review[k];else b.review[k]={...r,due:state.day+(stage===1?3:7),stage,lastDay:state.day};}}}
selectQ=(id,index)=>{let q=qObject(id),key=bankKey(id);if(!q||state.bank.attempts[key])return;let confidence=state.bank.confidence[key];if(!confidence)return alert('先选择“没把握 / 有些把握 / 很有把握”，再提交选项。');let a={id,choice:index,correct:index===q.a,day:state.day,confidence,time:new Date().toISOString(),context:key};state.bank.attempts[key]=a;state.bank.history.push(a);if(nav==='today')state.quizAnswers[state.day+'-'+id]=index;scheduleReview(q,a.correct);if(!a.correct){state.lastWrong=`第 ${state.day} 天 ${q.topic}：${id}，${q.angle||'概念辨析'}；需核对条件与中介。`;state.wrong[id]={due:state.day+1,stage:0}}else if(state.wrong[id]){delete state.wrong[id]}save();render();};
renderQuizQuestion=id=>{let q=qObject(id);if(!q)return '';let key=bankKey(id),a=state.bank.attempts[key];return `<article class="card bank-question" id="question-${q.id}">${questionMeta(q)}<h3>${esc(q.q)}</h3>${q.statements?`<div class="statements">${q.statements.map((s,i)=>`<p><strong>${'①②'[i]}</strong> ${esc(s)}</p>`).join('')}</div>`:''}${qLinks(q)}<label for="confidence-${q.id}">作答前的把握程度</label><select id="confidence-${q.id}" data-confidence="${q.id}" ${a?'disabled':''}><option value="">请选择</option>${['没把握','有些把握','很有把握'].map(v=>`<option ${state.bank.confidence[key]===v?'selected':''}>${v}</option>`).join('')}</select>${q.o.map((o,i)=>`<button class="choice ${a?(i===q.a?'correct':i===a.choice?'wrong':''):''}" type="button" data-q="${id}" data-answer="${i}" ${a?'disabled':''}>${'ABCD'[i]}. ${esc(o)}</button>`).join('')}${a?`<div class="notice ${a.correct?'':'danger'}"><strong>${a.correct?'答对':'答错'} · 答案 ${'ABCD'[q.a]} · 作答前：${esc(a.confidence)}</strong><p>这是本次作答结果；仍需闭书说明理由。正确选择不等于已经掌握论述。</p></div><details open><summary>解题思路与逐项解析</summary><p>${esc(q.why)}</p>${q.ex.map((ex,i)=>`<div class="optionwhy"><strong>${'ABCD'[i]} ${i===q.a?'应选':'不选'}：</strong>${esc(ex)}</div>`).join('')}</details><details><summary>误区怎样改写</summary><p>${esc(q.remedy)}</p></details><details open><summary>知识补课：回到概念与论证</summary><p>${esc(q.lesson)}</p><div class="notice warn"><strong>核查／边界：</strong>${esc(UNITS.get(q.kp[0]).boundary)}</div><p><strong>闭书回忆：</strong>${esc(q.recall)}</p></details>${questionTools(q)}`:'<p class="small muted">先独立判断。提交后显示四个选项的分析及相关微课。</p>'}</article>`};
function renderWritten(q,daily=false){let key=(daily?'D'+state.day:'P'+state.bank.session)+'|'+q.id,shown=state.bank.revealed[key];let self=state.bank.selfAttempts[key],total=q.rubric.reduce((n,r)=>n+r.score,0);return `<article class="card bank-question" id="question-${q.id}" data-writing-key="${key}">${questionMeta(q)}<h3>${esc(q.title)}</h3><p class="small muted">完整作答建议 ${q.minutes} 分钟。${daily?'今天任务：'+esc(day().writtenMode)+'，按本环节预算安排；完整答案训练可在选做时完成。':''}</p>${qLinks(q)}<label for="confidence-${q.id}">独立作答前的把握程度</label><select id="confidence-${q.id}" data-confidence="${q.id}" ${shown?'disabled':''}><option value="">请选择</option>${['没把握','有些把握','很有把握'].map(v=>`<option ${state.bank.confidence[key]===v?'selected':''}>${v}</option>`).join('')}</select><div class="notice">${esc(q.audit)}<br>示范结构：${esc(q.structure)}</div><details ${state.day<=14?'open':''}><summary>${state.day<=14?'前期示范提示：':'需要时再打开提示：'}答题步骤</summary>${q.outline.map((x,i)=>`<p>${i+1}. ${esc(x)}</p>`).join('')}</details><label for="draft-${q.id}">先写自己的答案或提纲（自动保存）</label><textarea id="draft-${q.id}" data-draft="${key}" placeholder="先说明问题，再写关键论证；至少写一句自己的分析后核对。">${esc(state.bank.drafts[key]||'')}</textarea><button class="btn" data-reveal="${key}" type="button">保存并核对参考答案</button>${shown?`<section class="written-answer"><h3>考场参考答案（教师自拟）</h3>${q.answer.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}<details><summary>展开理解：各论证环节与易混点</summary>${q.expanded.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}</details><h3>逐点自评 · 教学模拟评分 ${total} 分</h3><p class="small muted">只勾选自己答案中已经写出的要点；这是自评，不是自动阅卷或院校评分。</p>${q.rubric.map((r,i)=>`<label class="rubric"><input type="checkbox" data-rubric="${q.id}" data-point="${i}" ${self?.checks?.includes(i)?'checked':''}> ${esc(r.text)}（${r.score} 分）</label>`).join('')}<p class="notice">我的自评：<strong>${self?self.score+' / '+total:'尚未保存'}</strong></p><button class="btn secondary" data-self="${q.id}" type="button">保存本题自评</button><div class="notice warn"><strong>常见失分：</strong>${esc(q.loss)}</div><p><strong>其他可接受答法：</strong>${esc(q.accepted)}</p><details><summary>变式迁移：换个问题再答</summary><p>${esc(q.variation)}</p><label for="transfer-${q.id}">我的变式回答</label><textarea id="transfer-${q.id}" data-qnote="${q.id+'-transfer'}">${esc(state.bank.notes[q.id+'-transfer']||'')}</textarea><p class="small muted">检查标准：保留原题概念关系，说明变式改变了哪些条件，不直接复制原答案。</p></details>${questionTools(q)}`:''}</article>`}
function chapterSelect(options,selected){return options.map(([v,t])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(t)}</option>`).join('')}
function allBankQuestions(){return [...DATA.quiz,...DATA.essays]}
function filteredBank(){let f=state.bank.filters;return allBankQuestions().filter(q=>
(f.chapter==='all'||q.chapter===f.chapter)&&(f.kind==='all'||q.kind===f.kind)&&(f.priority==='all'||q.priority===f.priority)&&(f.difficulty==='all'||q.difficulty===f.difficulty)&&
(f.topic==='all'||f.topic==='跨理论比较'&&(q.kind==='比较'||q.angle==='跨理论比较'||q.q?.match(/阿多诺|哈贝马斯|卢卡奇|弗洛姆|鲍德里亚/)&&q.angle==='反例与评价')||f.topic==='综合应用'&&(q.kind==='材料分析'||q.angle==='情境应用')||f.topic==='核心概念'&&q.kind!=='材料分析'&&q.kind!=='比较'||(q.kp||[]).includes(f.topic))&&
(!f.search||(q.q||q.title||'').includes(f.search)||q.topic.includes(f.search)||q.id.toLowerCase().includes(f.search.toLowerCase()))&&
(state.bank.mode!=='收藏'||state.bank.marks[q.id])&&(state.bank.mode!=='错题'||q.kind==='选择题'&&(q.kp||[]).some(k=>state.bank.review[k])||q.kind!=='选择题'&&state.bank.essayReview[q.id]));}
function startBank(ids){state.bank.queue=ids;state.bank.cursor=0;state.bank.session++;save();renderQuestions()}
renderQuestions=()=>{let b=state.bank,qs=filteredBank(),stat=firstStats(),weak=weakUnits();const written=Object.values(b.self);let selfPct=written.length?Math.round(written.reduce((n,x)=>n+x.score/x.total,0)/written.length*100):null;
let top=titleCard('专题练习与答案',`${DATA.quiz.length} 道选择题 · ${DATA.essays.length} 道主观题 · ${DATA.knowledge.length} 个知识单元。重点是教学重要性，不代表某校出题频率。`)+`<div class="card"><div class="row"><span class="pill">选择题已练 ${stat.done}/${DATA.quiz.length}</span><span class="pill">首答正确率 ${stat.rate===null?'尚无':stat.rate+'%'}</span><span class="pill">大题已自评 ${written.length}；平均得分比例 ${selfPct===null?'尚无':selfPct+'%'}</span></div><p class="small muted">首答正确率只计算每题第一次作答；重复练习记录另存。大题自评与选择题成绩分开，不把看过答案计为练习。</p>${weak.length?`<div class="notice warn"><strong>薄弱单元（各题最近作答，含题量）：</strong>${weak.slice(0,5).map(x=>`${esc(x.u.term)} ${x.rate}% / ${x.done}题`).join('；')}</div>`:''}<div class="row">${['专题','混合','错题','收藏','覆盖表'].map(m=>`<button class="btn ${b.mode===m?'':'secondary'}" data-bankmode="${m}" type="button">${m}${m==='错题'?'再练':''}</button>`).join('')}</div><div class="filters">${[
['chapter','章节',[['all','全部章节'],['base','零基础'],...DATA.chapters.map(c=>[c.key,c.name])]],
['topic','专题',[['all','全部专题'],['核心概念','核心概念专题'],['跨理论比较','跨理论比较'],['综合应用','综合应用'],...DATA.knowledge.map(u=>[u.id,u.term])]],
['kind','题型',[['all','全部题型'],...['选择题','名词解释','简答','比较','论述','材料分析'].map(x=>[x,x])]],
['priority','重点',[['all','全部重点'],...['核心必会','重点掌握','拓展理解'].map(x=>[x,x])]],
['difficulty','难度',[['all','全部难度'],...['入门','进阶','综合'].map(x=>[x,x])]]
].map(([k,label,opts])=>`<div><label for="filter-${k}">${label}</label><select id="filter-${k}" data-bankfilter="${k}">${chapterSelect(opts,b.filters[k])}</select></div>`).join('')}<div><label for="bank-search">关键词或编号</label><input id="bank-search" type="text" value="${esc(b.filters.search)}"><button class="btn secondary" id="bank-search-go" type="button">搜索</button></div></div><p>匹配 ${qs.length} 题。选择题为理解训练，不假定目标院校有选择题。主观题均附独立提纲、完整答案及教学评分。</p><div class="row"><button class="btn" id="start-bank" type="button" ${qs.length?'':'disabled'}>${b.mode==='混合'?'开始交错练习（最多8题）':b.mode==='错题'?'开始到期变式（最多6题）':'开始所选专题（最多8题）'}</button><button class="btn secondary" id="clear-bank" type="button">返回目录</button></div></div>`;
if(b.mode==='覆盖表')top+=renderCoverage();
else if(b.queue.length){let id=b.queue[Math.min(b.cursor,b.queue.length-1)],q=QUESTIONS.get(id);top+=`<div class="card row between"><strong>本组 ${b.cursor+1}/${b.queue.length} · 当前位置已保存</strong><div class="row"><button class="btn secondary" data-cursor="-1" type="button" ${b.cursor===0?'disabled':''}>上一题</button><button class="btn" data-cursor="1" type="button" ${b.cursor===b.queue.length-1?'disabled':''}>下一题</button></div></div>`+(q.kind==='选择题'?renderQuizQuestion(id):renderWritten(q));}
else{let p=b.page||0;top+=`<div class="card"><h2>题目目录 · 每页20题</h2>${qs.slice(p*20,p*20+20).map(q=>`<button class="bank-tile" data-openq="${q.id}" type="button">${priorityTag(q.priority)} <span class="small">${esc(q.kind)} · ${esc(q.difficulty)} · ${q.id}</span><br>${esc(q.q||q.title)}</button>`).join('')||'<p>没有符合条件的题目。可调整筛选或到专题页选择。</p>'}<div class="row"><button class="btn secondary" data-page="-1" type="button" ${p===0?'disabled':''}>上一页</button><span>第 ${p+1} 页</span><button class="btn secondary" data-page="1" type="button" ${(p+1)*20>=qs.length?'disabled':''}>下一页</button></div></div>`;}
top+=`<details class="card"><summary>经核验的相关基础真题（${DATA.real.length}道；非西马专题）</summary><p>本轮没有新增可核验的西马专题院校题。全部题库自编题为模拟题。</p>${DATA.real.map(q=>`<p><strong>${esc(q.school)} ${q.year} · ${esc(q.subject)}</strong><br>${esc(q.format)}：${esc(q.title)}（原卷${q.officialScore}分，第1页第1题）<br><a href="${q.url}" target="_blank" rel="noopener">学校原卷</a> · ${esc(q.verified)}</p><details><summary>教师自拟参考答案与评分</summary><p>${esc(q.answer)}</p><p>${esc(q.points)}</p></details>`).join('')}</details>`+footer();$('main').innerHTML=top;bindBank();
document.querySelectorAll('[data-bankmode]').forEach(x=>x.onclick=()=>{b.mode=x.dataset.bankmode;b.queue=[];b.page=0;save();renderQuestions()});document.querySelectorAll('[data-bankfilter]').forEach(x=>x.onchange=()=>{b.filters[x.dataset.bankfilter]=x.value;b.page=0;b.queue=[];save();renderQuestions()});$('bank-search-go').onclick=()=>{b.filters.search=$('bank-search').value.trim();b.queue=[];b.page=0;save();renderQuestions()};$('bank-search').onkeydown=e=>{if(e.key==='Enter')$('bank-search-go').click()};$('clear-bank').onclick=()=>{b.queue=[];save();renderQuestions()};$('start-bank').onclick=()=>{let chosen=qs;if(b.mode==='错题'){chosen=qs.filter(q=>q.kind==='选择题'?q.kp.some(k=>b.review[k]&&(b.review[k].due<=state.day||state.day===45)):b.essayReview[q.id]&&(b.essayReview[q.id].due<=state.day||state.day===45));if(!chosen.length)return alert('当前没有到期题。可在目录提前选做；学习日推进后到期题会出现。');}if(b.mode==='混合'){let group=new Map();chosen.forEach(q=>{let a=group.get(q.chapter)||[];a.push(q);group.set(q.chapter,a)});let arrays=[...group.values()].map(arr=>arr.sort((a,b)=>(state.bank.history.filter(h=>h.id===a.id).length-state.bank.history.filter(h=>h.id===b.id).length)));let shift=b.session%Math.max(1,arrays.length);arrays=[...arrays.slice(shift),...arrays.slice(0,shift)];chosen=[];for(let i=0;i<8;i++)for(let arr of arrays)if(arr[i])chosen.push(arr[i]);}chosen=[...chosen].sort((a,b)=>state.bank.mode==='混合'?0:((state.bank.history.some(x=>x.id===a.id)?1:0)-(state.bank.history.some(x=>x.id===b.id)?1:0)));startBank(chosen.slice(0,b.mode==='错题'?6:8).map(q=>q.id))};document.querySelectorAll('[data-openq]').forEach(x=>x.onclick=()=>startBank([x.dataset.openq]));document.querySelectorAll('[data-cursor]').forEach(x=>x.onclick=()=>{b.cursor=Math.max(0,Math.min(b.queue.length-1,b.cursor+Number(x.dataset.cursor)));save();renderQuestions();window.scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{b.page+=Number(x.dataset.page);save();renderQuestions()});};
function renderCoverage(){return `<div class="card"><h2>知识点 → 讲解 → 题目 → 复习</h2><p>原文1225段均纳入范围映射；原文保留，单元微课与争议核查另列。每个教学单元至少四道不同角度的题，另有四选一综合训练。微小课堂例子不另冒充独立考点。建议复习日可选，答错再按表现调整。</p>${DATA.knowledge.filter(u=>state.bank.filters.chapter==='all'||state.bank.filters.chapter===u.chapter).map(u=>`<details><summary>${priorityTag(u.priority)} ${u.id} · ${esc(u.term)}</summary><p>依据：${esc(u.reason)}。原文：${esc(u.ref)}；首次第${u.learnDays.join('、')}天；建议再练第${u.reviewDays.join('、')}天。</p><button class="btn secondary" data-unit="${u.id}" type="button">单元微课与核查</button><p>练习角度：${u.quizIds.map((id,i)=>`<button class="source-link" data-openq="${id}" type="button">${esc(QUESTIONS.get(id).angle)} ${id}</button>`).join('；')}</p><p>主观题：${u.essayIds.map(id=>`<button class="source-link" data-openq="${id}" type="button">${id}</button>`).join('；')}</p></details>`).join('')}</div>`}
const ANGLE_NAMES=['概念与边界','论证与易混','情境应用','反例与评价'];
function openBankModal(title,body){$('sourceModal').querySelector('h2').textContent=title;$('modalBody').innerHTML=body;$('sourceModal').classList.add('open');$('sourceModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('closeSource').focus();}
function unitModal(id){let u=UNITS.get(id);if(!u)return;openBankModal('单元微课 · '+u.term,`${priorityTag(u.priority)}<p><span class="tag tag-extra">教学重构，非原文</span> ${esc(u.definition)}</p><h3>论证线索</h3><ol>${u.chain.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="notice warn"><strong>原笔记核查／争议／边界</strong><p>${esc(u.boundary)}</p></div>${(u.auditIds||[]).map(id=>{let n=DATA.audits.find(x=>x.id===id);return `<div class="notice warn"><strong>${esc(n.status)} · ${esc(n.ref)}</strong><p>【原笔记说法／概括】${esc(n.original)}</p><p>【核查／补充】${esc(n.note)}</p></div>`}).join('')}<p>${esc(u.case)}</p><p>${esc(u.status)}。核查资料：${u.refs.map(id=>{let r=DATA.refs.find(r=>r.id===id);return r?`<a href="${r.url}" target="_blank" rel="noopener">${esc(id+' '+r.label)}</a>`:esc(id)}).join('；')}</p><div class="row"><button class="btn secondary" data-lecture="${id}" type="button">展开背景讲义</button><button class="btn secondary" data-range="${esc(u.ref)}" type="button">看对应原文</button></div>`);}
function lectureModal(id){let u=UNITS.get(id);if(!u)return;if(u.chapter==='base'){let f=DATA.foundations[u.foundation];openBankModal('基础讲义 · '+f.term,`<p>${esc(f.plain)}</p><p>${esc(f.strict)}</p><p>例子：${esc(f.example)}</p><div class="notice warn">${esc(f.mistake)}</div><p>自问：${esc(f.question)}</p><details><summary>核对</summary><p>${esc(f.answer)}</p></details>`);return}let c=DATA.chapters.find(c=>c.key===u.chapter);let section=c.sections[u.lessonSection];openBankModal('相关讲义 · '+c.name,`<p>从“${esc(u.term)}”进入，下面是背景展开；直接对应的解释见单元微课。</p><p>${esc(u.definition)}</p><h3>${esc(section.title)}</h3>${section.html}<details><summary>整章主线</summary>${c.intro}</details><button class="btn secondary" data-unit="${id}" type="button">回到单元微课</button>`);}
let sourcePage=0,sourceRange='';
function openRange(ref,page=0){sourceRange=ref;sourcePage=page;let ids=sourceIds(ref.replace(/[—–]/g,'-')),start=page*35;openBankModal('对应原笔记 · '+ref,`<p>【原笔记原文】保留原用字，不表示认可其中所有说法。范围共${ids.length}段，每页35段。</p>${ids.slice(start,start+35).map(i=>sourceItem(i)+Object.entries(DATA.imagePositions).filter(([g,p])=>p===DATA.source[i-1].id).map(([g,p])=>`<img class="img-note" src="${DATA.images[g]}" alt="原笔记图${g}"><p class="small muted">原图${g}；手写不清处不据常识补写。</p>`).join('')).join('')}<div class="row"><button class="btn secondary" data-sourcepage="-1" type="button" ${page===0?'disabled':''}>前35段</button><button class="btn secondary" data-sourcepage="1" type="button" ${start+35>=ids.length?'disabled':''}>后35段</button></div>`);}
const oldCloseSource=$('closeSource').onclick;$('closeSource').onclick=()=>{oldCloseSource();document.body.style.overflow='';document.querySelector('.bank-question h3')?.scrollIntoView({block:'nearest'});};
function bindBank(){document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>selectQ(b.dataset.q,+b.dataset.answer));document.querySelectorAll('[data-confidence]').forEach(e=>e.onchange=()=>{state.bank.confidence[bankKey(e.dataset.confidence)]=e.value;save()});document.querySelectorAll('[data-draft]').forEach(e=>e.oninput=()=>{state.bank.drafts[e.dataset.draft]=e.value;save()});document.querySelectorAll('[data-qnote]').forEach(e=>e.oninput=()=>{state.bank.notes[e.dataset.qnote]=e.value;save()});document.querySelectorAll('[data-reveal]').forEach(e=>e.onclick=()=>{let key=e.dataset.reveal;if(!state.bank.confidence[key])return alert('先选择作答前的把握程度，再核对参考答案。');if((state.bank.drafts[key]||'').trim().length<12)return alert('请先写出至少一句自己的分析，再看参考答案。');state.bank.revealed[key]=true;save();render()});document.querySelectorAll('[data-self]').forEach(e=>e.onclick=()=>{let id=e.dataset.self,q=QUESTIONS.get(id);let checks=[...document.querySelectorAll(`[data-rubric="${id}"]:checked`)].map(x=>+x.dataset.point),score=checks.reduce((n,i)=>n+q.rubric[i].score,0),total=q.rubric.reduce((n,r)=>n+r.score,0);state.bank.self[id]={checks,score,total,day:state.day,confidence:state.bank.confidence[bankKey(id)]};state.bank.selfAttempts[bankKey(id)]={...state.bank.self[id]};if(score/total<.75)state.bank.essayReview[id]={due:state.day+1};else delete state.bank.essayReview[id];if(nav==='today')state.stepDone[doneKey(state.day,4)]=true;save();render()});document.querySelectorAll('[data-mark]').forEach(e=>e.onclick=()=>{let id=e.dataset.mark;state.bank.marks[id]=!state.bank.marks[id];save();render()});document.querySelectorAll('[data-repeat]').forEach(e=>e.onclick=()=>{if(nav==='today'){setNav('questions');startBank([e.dataset.repeat]);}else{state.bank.session++;save();renderQuestions()}});}
document.addEventListener('click',e=>{let t=e.target.closest('[data-unit],[data-lecture],[data-range],[data-sourcepage]');if(!t)return;if(t.dataset.unit)unitModal(t.dataset.unit);if(t.dataset.lecture)lectureModal(t.dataset.lecture);if(t.dataset.range)openRange(t.dataset.range);if(t.dataset.sourcepage)openRange(sourceRange,Math.max(0,sourcePage+Number(t.dataset.sourcepage)));});
function chooseVariant(unit,dayNum){let candidates=DATA.quiz.filter(q=>q.kp.includes(unit));let due=state.bank.review[unit];return candidates.sort((a,b)=>{let x=state.bank.history.filter(h=>h.id===a.id).length,y=state.bank.history.filter(h=>h.id===b.id).length;return x-y||(due?(a.angle==='情境应用'?-1:0)-(b.angle==='情境应用'?-1:0):Math.abs(a.plannedDays-dayNum)-Math.abs(b.plannedDays-dayNum))})[0]?.id;}
dailyQuiz=d=>{let b=state.bank;if(b.dayVersions[d.day]===2&&state.dayQuestions[d.day]?.every(id=>DATA.quiz.some(q=>q.id===id)))return state.dayQuestions[d.day];let count=d.weekly?3:2;let due=Object.entries(b.review).filter(([k,r])=>r.due<=d.day).sort((a,b)=>a[1].due-b[1].due);let ids=due.slice(0,1).map(([k])=>chooseVariant(k,d.day)).filter(Boolean);let priorWeek=7*Math.floor((d.day-1)/7);let score=state.weekly[priorWeek];let active=[...(d.knowledge||[])];if(score!==undefined&&score<75){let weak=weakUnits()[0];if(weak&&!active.includes(weak.u.id))active.unshift(weak.u.id);}let units=active.sort((a,b)=>{let aa=firstStats(DATA.quiz.filter(q=>q.kp.includes(a))),bb=firstStats(DATA.quiz.filter(q=>q.kp.includes(b)));return aa.done-bb.done;});for(let u of units){let id=chooseVariant(u,d.day);if(id&&!ids.includes(id))ids.push(id);if(ids.length>=count)break;}if(ids.length<count){for(let u of units)for(let id of UNITS.get(u).quizIds){if(!ids.includes(id))ids.push(id);if(ids.length>=count)break;}ids=ids.slice(0,count);}state.dayQuestions[d.day]=ids;b.dayVersions[d.day]=2;save();return ids;};
const oldStepTime=stepTime;stepTime=d=>d.day===43||d.day===44?[8,6,12,8,22,4,0]:oldStepTime(d);
const oldToday=renderToday;
renderToday=()=>{oldToday();let d=day();if(state.activeStep===3){let cards=document.querySelectorAll('.bank-question');if(cards.length){cards[0].insertAdjacentHTML('beforebegin',`<div class="notice">当天必做${dailyQuiz(d).length}题，预计${d.practiceBudget}分钟，含订正；到期队列${Object.values(state.bank.review).filter(r=>r.due<=d.day).length}个单元。超出今天预算的再练留到后续日，选做题从“题库”进入。</div>`);}}if(state.activeStep===4){let q=QUESTIONS.get(d.essay);let section=$('main').querySelector('section.card');section.innerHTML=renderWritten(q,true)+`<button class="btn" data-written-next type="button" ${state.stepDone[doneKey(d.day,4)]?'':'disabled'}>保存自评后，继续订正反思</button>`;section.querySelector('[data-written-next]').onclick=()=>{state.activeStep=5;save();render()};}if(state.activeStep===2){$('main').querySelector('section.card').insertAdjacentHTML('beforeend',`<div class="notice"><strong>本日直接对应的概念微课</strong><p>${(d.knowledge||[]).map(k=>`<button class="source-link" data-unit="${k}" type="button">${esc(UNITS.get(k).term)}</button>`).join('；')}</p><p class="small muted">读完继续“即时练习”，按当天预算选题；其余专题题属于选做。</p></div>`);}if(state.activeStep===0){let weak=weakUnits();$('main').querySelector('section.card').insertAdjacentHTML('afterbegin',`<p class="notice">今日核心单元：${(d.knowledge||[]).slice(0,6).map(k=>esc(UNITS.get(k).term)).join('、')+((d.knowledge||[]).length>6?'等；今天只精读书面题相关单元，其余作回忆线索':'')}。${weak.length?'可用回忆时间复述薄弱单元“'+esc(weak[0].u.term)+'”。':''}选做不计入必做60分钟。</p>`);}if(state.activeStep===5&&d.weekly){let s=firstStats(),current=state.bank.history.filter(a=>a.day>=d.day-6&&a.day<=d.day);let rate=current.length?Math.round(current.filter(a=>a.correct).length/current.length*100):null;$('main').querySelector('section.card').insertAdjacentHTML('afterbegin',`<div class="notice">本周小题${current.length}次，正确率${rate===null?'尚无':rate+'%'}；大题自评单独保存。下方填写综合表现，不将小题正确率直接等同论述水平。低于75%：下周增加5分钟回忆，并优先再练薄弱单元；75—89%保持节奏；90%以上可在相同预算内换综合变式。</div>`);}bindBank();};
function validateBackup(x){
 const obj=v=>v&&typeof v==='object'&&!Array.isArray(v),dayOK=d=>Number.isInteger(d)&&d>=1&&d<=45;
 if(!obj(x)||![1,2].includes(x.version)||!dayOK(x.day)||!Array.isArray(x.completed)||x.completed.some(d=>!dayOK(d))||!obj(x.stepDone))throw Error('版本或学习日格式不符');
 for(const k of ['writing','reflection','wrong','quizAnswers','dayQuestions','weekly'])if(x[k]!==undefined&&!obj(x[k]))throw Error(k+' 格式不符');
 if(x.activeStep!==undefined&&(!Number.isInteger(x.activeStep)||x.activeStep<0||x.activeStep>6))throw Error('学习环节格式不符');
 if(x.font!==undefined&&(!Number.isFinite(x.font)||x.font<16||x.font>24))throw Error('字号格式不符');
 for(const v of Object.values(x.weekly||{}))if(!Number.isFinite(v)||v<0||v>100)throw Error('每周评分格式不符');
 if(x.bank){let b=x.bank;if(!obj(b))throw Error('题库记录格式不符');
  for(let k of ['attempts','drafts','revealed','marks','notes','confidence','self','selfAttempts','review','essayReview','filters','dayVersions'])if(b[k]!==undefined&&!obj(b[k]))throw Error('题库 '+k+' 格式不符');
  if(b.history!==undefined&&!Array.isArray(b.history))throw Error('作答历史格式不符');
  const attempt=a=>{let q=QUESTIONS.get(a?.id);if(!obj(a)||!q||q.kind!=='选择题'||!dayOK(a.day)||!Number.isInteger(a.choice)||a.choice<0||a.choice>3||a.correct!==(a.choice===q.a)||!['没把握','有些把握','很有把握'].includes(a.confidence))throw Error('作答记录或答案格式不符');};
  for(let a of b.history||[])attempt(a);for(let a of Object.values(b.attempts||{}))attempt(a);
  for(let k of ['drafts','notes'])for(let v of Object.values(b[k]||{}))if(typeof v!=='string')throw Error('文本记录格式不符');
  for(let v of Object.values(b.confidence||{}))if(!['','没把握','有些把握','很有把握'].includes(v))throw Error('信心记录格式不符');
  for(let [id,v] of Object.entries(b.review||{}))if(!UNITS.has(id)||!obj(v)||!Number.isInteger(v.due)||v.due<1||v.due>366||!Number.isInteger(v.stage)||v.stage<0||v.stage>2)throw Error('概念再练记录格式不符');
  for(let [id,v] of Object.entries(b.essayReview||{}))if(!DATA.essays.some(q=>q.id===id)||!obj(v)||!Number.isInteger(v.due)||v.due<1||v.due>366)throw Error('大题再练记录格式不符');
  for(let field of ['self','selfAttempts'])for(let [id,v] of Object.entries(b[field]||{})){let q=QUESTIONS.get(field==='self'?id:id.split('|').at(-1));if(!obj(v)||!q?.rubric||!Array.isArray(v.checks)||v.checks.some(i=>!Number.isInteger(i)||i<0||i>=q.rubric.length)||new Set(v.checks).size!==v.checks.length||v.score!==v.checks.reduce((n,i)=>n+q.rubric[i].score,0)||v.total!==q.rubric.reduce((n,r)=>n+r.score,0))throw Error('大题自评格式不符');}
  if(b.queue!==undefined&&(!Array.isArray(b.queue)||b.queue.some(id=>!QUESTIONS.has(id))))throw Error('练习队列编号不符');
  for(let k of ['session','cursor','page'])if(b[k]!==undefined&&(!Number.isInteger(b[k])||b[k]<(k==='session'?1:0)))throw Error('练习位置格式不符');
 }return true;
}
const oldProgress=renderProgress;
renderProgress=()=>{oldProgress();let b=state.bank;for(let card of document.querySelectorAll('.card'))if(card.querySelector('h2')?.textContent==='错题再练队列')card.classList.add('hidden');let detail=`<div class="card"><h2>新版题库记录</h2><p>到期待练：${Object.values(b.review).filter(r=>r.due<=state.day).length}个概念；大题待再练${Object.keys(b.essayReview).length}道；收藏${Object.values(b.marks).filter(Boolean).length}道。</p><p>再练按学习日计时，答错次日出现；延迟答对后间隔3日、7日。当天重复不推进熟练阶段；到期优先换同一单元的其他问法。三轮正确只表示选择题再练暂结束，不表示论述掌握。</p>${Object.entries(b.review).map(([id,r])=>`<p>${esc(UNITS.get(id)?.term||id)} · 第${r.due}学习日再练 · 已完成${r.stage}轮延迟正确</p>`).join('')}<p class="small muted">45天后仍可在错题页自主再练。超出本周期的到期项在第45天开放选做，不把当天重复当成间隔掌握。</p><button class="btn" id="progress-bank" type="button">进入错题变式</button><details><summary>最近20次选择题作答（信心与正确性分开）</summary>${b.history.slice(-20).reverse().map(a=>`<p>${esc(a.id)} · 第${a.day}天 · ${a.correct?'正确':'错误'} · ${esc(a.confidence)}</p>`).join('')||'<p>尚无</p>'}</details><details><summary>我的题目解释和变式记录</summary>${Object.entries(b.notes).filter(([k,v])=>v).map(([k,v])=>`<p><strong>${esc(k)}</strong>：${esc(v)}</p>`).join('')||'<p>尚无</p>'}</details></div>`;$('main').querySelector('.hero').insertAdjacentHTML('afterend',detail);$('progress-bank').onclick=()=>{b.mode='错题';b.queue=[];save();setNav('questions')};$('confirmRestore').onclick=()=>{if(!pendingBackup)return;state=Object.assign(fresh(),pendingBackup);pendingBackup=null;normalizeBank();save();render()};let prepare=x=>{validateBackup(x);pendingBackup=x;$('restoreConfirm').classList.remove('hidden');$('restoreConfirm').querySelector('strong').textContent=`备份校验通过：第${x.day}天、${x.completed.length}天已完成、${x.bank?.history?.length||0}次新版作答。覆盖当前记录前请保存备份。`;};$('restorePasted').onclick=()=>{try{prepare(JSON.parse($('restoreText').value))}catch(e){pendingBackup=null;alert('备份无效：'+e.message)}};$('importFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{prepare(JSON.parse(await f.text()))}catch(e){pendingBackup=null;alert('备份无效：'+e.message)}};};
function bankForUnit(id){state.bank.filters={...bankFresh().filters,chapter:UNITS.get(id).chapter,topic:id};state.bank.mode='专题';state.bank.queue=[];state.bank.page=0;save();setNav('questions');}
document.addEventListener('click',e=>{let t=e.target.closest('[data-unitpractice]');if(t)bankForUnit(t.dataset.unitpractice);});
const oldChapters=renderChapters;renderChapters=()=>{oldChapters();let units=DATA.knowledge.filter(u=>u.chapter===state.readerChapter);let section=$('main').querySelector('.card');if(section)section.insertAdjacentHTML('beforeend',`<h3>按知识单元继续理解与练习</h3>${units.map(u=>`<details><summary>${priorityTag(u.priority)} ${esc(u.term)}</summary><p>${esc(u.definition)}</p><p>论证线索：${esc(u.chain.join(' → '))}</p><div class="row"><button class="btn secondary" data-unit="${u.id}" type="button">讲解与核查</button><button class="btn" data-unitpractice="${u.id}" type="button">练本单元</button></div></details>`).join('')}`);bindBank();};
const oldRender=render;render=()=>{normalizeBank();oldRender();bindBank()};
